### ISSUE TITLE
Create issues from changelogs automatically

### ISSUE THREAD

**Issue by sabbelasichon** [andreaswolf/fractor#107]
For TYPO3-Rector we have a neat little repo https://github.com/sabbelasichon/typo3-rector-issue-generator to generate issues from the changelogs automatically.

**Comment by sabbelasichon** [comment]
@simonschaufi I am wondering if it would be ok, if we just collect the issues in TYPO3-Rector and label them with Fractor. It would make things a lot easier.

**Comment by simonschaufi** [comment]
Yes, otherwise we have to go through the issues 2x.

I've already added a label for it: https://github.com/sabbelasichon/typo3-rector/issues?q=is%3Aissue+is%3Aopen+label%3AFractor
