### ISSUE TITLE
Running RemoveTceFormsDomElementFlexFormFractor changes EOF

### ISSUE THREAD

**Issue by simonschaufi** [andreaswolf/fractor#198]
Applied rules:
RemoveTceFormsDomElementFlexFormFractor (https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-97126-TCEformsRemovedInFlexForm.html)

This should not happen:

```diff
    ---------- begin diff ----------
-</T3DataStructure>
+</T3DataStructure>
    ----------- end diff -----------

**Comment by andreaswolf** [comment]
Not sure what we could do here, is there an "EOF" option for the XML Pretty Printer?
