### ISSUE TITLE
File counter is not correct

### ISSUE THREAD

**Issue by simonschaufi** [andreaswolf/fractor#199]
First it counts up to 650:

```bash
vendor/bin/fractor process --dry-run
  65/650 [==>-------------------------]  10%
```
and then it goes up way above 1000:

```bash
vendor/bin/fractor process --dry-run
 1078/1078 [============================] 10
```
and does weird things

**Comment by andreaswolf** [comment]
I suppose this is because currently the progress is advanced for each file and for each processor, not only once per file.
