### ISSUE TITLE
TypoScript rule changes `[end]` to `[global]`

### ISSUE THREAD

**Issue by simonschaufi** [andreaswolf/fractor#200]
this should not happen:

```diff
 [siteLanguage('languageId') == 1]
-       page.jsInline.5.value = var language = 'en';
-[end]
-
+page.jsInline.5.value = var language = 'en';
+[global]
```

**Comment by andreaswolf** [comment]
Not sure why this happens. This is probably a thing that the TS pretty printer does, but in general the statements like `[end]` should be kept.

**Comment by simonschaufi** [comment]
This also occurs in TYPO3 Rector 1.0. Seams like a bug in the third party lib.

**Comment by simonschaufi** [comment]
This is a bug in the TS parser and printer from Helmich and can't be fixed on our side.
