### ISSUE TITLE
Run fractor in "standalone" directory

### ISSUE THREAD

**Issue by wtfred** [andreaswolf/fractor#233]
Hello there,

Sorry in advance if i'm doing something wrong here.
I'm updating my "template" for TYPO3 project, with all dev tools i'm using, and i want to start using Fractor.

Running into [this issue](https://github.com/sabbelasichon/typo3-rector/issues/4247) with typo3-rector, i moved dev tools from my project composer dev dependencies to standalone directories, as i was advised in the issue, and also in the [recommanded way of php-cs-fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer?tab=readme-ov-file#installation)

I tried to do the same thing with Fractor, and install it in a standalone directory, but when i try to run it, i got this error:

```
PHP Fatal error:  Uncaught Error: Class "a9f\Fractor\Configuration\ConfigResolver" not found in /var/www/html/.tools/fractor/vendor/a9f/fractor/bin/fractor.php:29
```
From what i understand, it comes from this line https://github.com/andreaswolf/fractor/blob/main/packages/fractor/bin/fractor.php#L12 that makes the binary loading my project autoload first, and not the autoload from the "standalone directory"

Once again, sorry if i'm doing something wrong, i'm starting to use both Fractor and this standalone directory method both together so...

Thanks!

**Comment by wtfred** [comment]
A bit more info on this issue, and i also found a workaround.

In my project directory, i have a `tools` folder, like this:
```
tools/fractor
tools/typo3-coding-standards
tools/typo3-rector
```
To execute `rector`, i can do `tools/typo3-rector/vendor/bin/rector process --dry-run`
To execute `phpstan`, i can do `tools/typo3-rector/vendor/bin/phpstan`
To execute `php-cs-fixer`, i can do `tools/typo3-coding-standards/vendor/bin/php-cs-fixer check`

If i try to run `fractor` with `tools/fractor/vendor/bin/fractor process --dry-run`, i got the error mentioned above

As a workaround, i have to do this:
```
cd tools/fractor
vendor/bin/fractor process --dry-run -c ../../fractor.php
```

**Comment by simonschaufi** [comment]
Do you use one compoer.json for all tools or does each tool has its own composer.json file?

**Comment by wtfred** [comment]
Each tool has its own composer.json
I'm currently test that structure, before i had all tools in require-dev of the project
Now i want to make it standalone (inside the project) so it won't be impacted by some dependencies conflict.
I have something like this, and in `.php-cs-fixer.dist.php`, `rector.php` `fractor.php` and `phpstan.neon` i'm targeting only `packages/`

```
project
├── .editorconfig
├── .env
├── .env.dist
├── .gitignore
├── .gitlab-ci.yml
├── .php-cs-fixer.cache
├── .php-cs-fixer.dist.php
├── .tools
│   ├── fractor
│   │   ├── composer.json
│   │   ├── composer.lock
│   │   └── vendor
│   ├── typo3-coding-standards
│   │   ├── composer.json
│   │   ├── composer.lock
│   │   └── vendor
│   └── typo3-rector
│       ├── composer.json
│       ├── composer.lock
│       ├── public
│       └── vendor
├── composer.json
├── composer.lock
├── config/
├── fractor.php
├── packages/
├── phpstan.neon
├── public/
├── rector.php
├── var/
└── vendor/
```

**Comment by wtfred** [comment]
After more tests, i think this issue is not relevant.

With the structure above, i'm adding some `scripts` into my `composer.json`

```json
"check": [
	"@check:rector",
	"@check:fractor",
	"@check:cs",
	"@check:phpstan"
],
"check:phpstan": [
	"@composer -d $(pwd)/.tools/typo3-rector exec -- vendor/bin/phpstan analyse -c $(pwd)/phpstan.neon"
],
"check:rector": [
	"@composer -d $(pwd)/.tools/typo3-rector exec -- vendor/bin/rector process -c $(pwd)/rector.php --dry-run"
],
"check:cs": [
	"@composer exec -- .tools/typo3-coding-standards/vendor/bin/php-cs-fixer check --diff"
],
"check:fractor": [
	"@composer -d $(pwd)/.tools/fractor exec -- vendor/bin/fractor process -c $(pwd)/fractor.php --dry-run"
],
"fix": [
	"@fix:rector",
	"@fix:fractor",
	"@fix:cs"
],
"fix:rector": [
	"@composer -d $(pwd)/.tools/typo3-rector exec -- vendor/bin/rector process -c $(pwd)/rector.php"
],
"fix:cs": [
	"@composer exec -- .tools/typo3-coding-standards/vendor/bin/php-cs-fixer fix"
],
"fix:fractor": [
	"@composer -d $(pwd)/.tools/fractor exec -- vendor/bin/fractor process -c $(pwd)/fractor.php"
],
"t3cs:update": [
	"@composer exec -- .tools/typo3-coding-standards/vendor/bin/typo3-coding-standards update"
]
```

And i have some tools i can use with `composer check:fractor`,

Or using ddev `ddev composer check:fractor`

Or in my gitlab CI:
```
analyse:
  stage: analyse
  rules:
    - changes:
        - packages/**/*
  before_script: [ ]
  script:
    - *composer-auth
    - composer install
    - composer check

```

**Comment by simonschaufi** [comment]
Closing this as not a valid bug. Works as expected.
