### ISSUE TITLE
Support changing TypoScript files

### ISSUE THREAD

**Issue by sabbelasichon** [andreaswolf/fractor#25]
We should use typo3cms/core with the new TypoScriptParser

**Comment by sabbelasichon** [comment]
- https://github.com/sabbelasichon/typo3-rector/blob/1.x/src/FileProcessor/TypoScript/Rector/v10/v0/ExtbasePersistenceTypoScriptRector.php
- https://github.com/sabbelasichon/typo3-rector/blob/1.x/src/FileProcessor/TypoScript/Rector/v11/v0/TemplateToFluidTemplateTypoScriptRector.php
- https://github.com/sabbelasichon/typo3-rector/blob/1.x/src/FileProcessor/TypoScript/Rector/v12/v0/RemoveDisableCharsetHeaderConfigTypoScriptRector.php

**Comment by simonschaufi** [comment]
If we use the dependency from the core itself, we will have the challenge that there will be an old parser and a new parser, so we will always depend on the TYPO3 version which is installed. I already talked with Christian Kuhn and Martin Helmich about this and Christian said that the new TypoScript parser won't become a standalone package soon even though this would be the best for us as we could then directly depend on the new parser but the new Parser has too many dependencies to the core atm. So either we use the parser from Martin or extract the new parser by ourselves or add a feature detection which parser is in use if we add the dependency from the core.

**Comment by sabbelasichon** [comment]
@andreaswolf I am going to close this issue for now
