### ISSUE TITLE
Did you consider using XSLT for transforming XML?

### ISSUE THREAD

**Issue by BenjaminBeck** [andreaswolf/fractor#27]
![image](https://github.com/andreaswolf/fractor/assets/1185872/f6588f97-760c-4a65-b141-14159fccd4aa)

**Comment by sabbelasichon** [comment]
What is your use case? We didn´t think about that.

**Comment by andreaswolf** [comment]
Not 100% related, but we might want to make the file extensions for the XML FileProcessor configurable, to also allow covering .xsl files or other XML files.
