### ISSUE TITLE
Define release workflow

### ISSUE THREAD

**Issue by andreaswolf** [andreaswolf/fractor#40]
Things to consider:

* how do we change requirements for other packages from this repo? Fix them to the exact version or require the same minor version (e.g. for 0.1.2 we would change the requirement to ^0.1 for all dependencies)
* how to automate releases? => Most of the work should be done by GitHub and Packagist already
* how to document releases? Change log? GitHub releases?
* Add correct version in FractorApplication (https://github.com/andreaswolf/fractor/blob/main/fractor/src/FractorApplication.php#L13)

**Comment by sabbelasichon** [comment]
What do you think about: https://github.com/symplify/monorepo-builder

**Comment by sabbelasichon** [comment]
To set the version have a look at https://github.com/TYPO3-Console/TYPO3-Console/blob/main/Classes/Console/Composer/ScriptHelper.php as inspiration
