### ISSUE TITLE
Support changing YAML files

### ISSUE THREAD

**Issue by andreaswolf** [andreaswolf/fractor#5]
Since YAML is a pretty widespread configuration syntax, changing it e.g. in the course of a project upgrade is a key feature. Therefore, Fractor should support that.

There is the symfony/yaml library for decoding and encoding YAML, but that does not give us an AST, and it does not preserve any formatting options.
Apart from that, I did not find any PHP YAML libraries that offer more features in a quick search.

There is https://www.npmjs.com/package/yaml-ast-parser and a newer fork https://www.npmjs.com/package/@stoplight/yaml-ast-parser which seem to support the relevant features.

**Comment by sabbelasichon** [comment]
We could start simple and just use the array structure of yaml but trying to keep the format with this neat little trick: https://github.com/sabbelasichon/typo3-rector/blob/1.x/src/FileProcessor/Yaml/YamlFileProcessor.php#L102C70-L102C83
