### ISSUE TITLE
Support changing composer.json files

### ISSUE THREAD

**Issue by andreaswolf** [andreaswolf/fractor#7]
Same as #5, we should have support for changing JSON files with keeping the formatting as much intact as possible.

**Comment by sabbelasichon** [comment]
Maybe have a look at: https://github.com/eta-orionis/composer-json-manipulator

**Comment by sabbelasichon** [comment]
https://github.com/efabrica-team/rector-composer

**Comment by sabbelasichon** [comment]
Have a look at https://github.com/sabbelasichon/typo3-rector/blob/v0.9.21/config/composer/typo3-104-composer-packages-core.php
